# Generated by Django 4.2 on 2023-04-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=1, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=1),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=1, max_length=14, null=1, unique=1),
            preserve_default=1,
        ),
    ]
