# Generated by Django 4.2 on 2023-04-19 14:11

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_user_gender_user_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_1',
            field=phonenumber_field.modelfields.PhoneNumberField(default='201111111111', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=1, max_length=128, null=1, region=None),
            preserve_default=1,
        ),
    ]
