# Generated by Django 4.1.7 on 2023-04-02 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentMedication',
            fields=[
                ('medication_id', models.AutoField(primary_key=True, serialize=False)),
                ('Appointment_id', models.IntegerField()),
                ('time_date', models.DateTimeField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Dispensing',
            fields=[
                ('dispensin_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('drug_form', models.CharField(max_length=50)),
                ('brand_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('company', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100, null=True)),
                ('stock_level', models.IntegerField()),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pharmacist_license', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DrugReDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('frquency', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('dispense', models.IntegerField()),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy.drug')),
                ('medication_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DrugReDetail', to='Pharmacy.currentmedication')),
            ],
        ),
        migrations.CreateModel(
            name='DispensingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispensin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy.dispensing')),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy.drug')),
            ],
        ),
        migrations.AddField(
            model_name='dispensing',
            name='Pharmacist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy.pharmacist'),
        ),
        migrations.AddField(
            model_name='dispensing',
            name='medication_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy.currentmedication'),
        ),
    ]
