# Generated by Django 4.1.7 on 2023-04-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
