# Generated by Django 4.2 on 2023-04-19 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Hospital', '0001_initial'),
        ('Appointments', '0001_initial'),
        ('Pharmacy', '0001_initial'),
        ('Lab_Radiology', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicineService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MedicineService', to='Bills.bill')),
                ('medication_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MedicineService', to='Pharmacy.currentmedication')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('number', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('coverage', models.CharField(max_length=50)),
                ('card', models.ImageField(upload_to='Bills/file/media')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InsuranceDetails', to='Hospital.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ExamService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ExamService', to='Bills.bill')),
                ('exam_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ExamService', to='Lab_Radiology.examrequest')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Bill', to='Bills.insurancedetails'),
        ),
        migrations.AddField(
            model_name='bill',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bill', to='Hospital.patient'),
        ),
        migrations.CreateModel(
            name='AppointmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AppointmentService', to='Appointments.bookedappointment')),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AppointmentService', to='Bills.bill')),
            ],
        ),
    ]
