# Generated by Django 4.1.7 on 2023-04-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancedetails',
            name='coverage',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='insurancedetails',
            name='number',
            field=models.CharField(max_length=30),
        ),
    ]
