# Generated by Django 4.1.7 on 2023-04-02 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Appointments', '0002_initial'),
        ('Pharmacy', '0001_initial'),
        ('Hospital', '0001_initial'),
        ('Bills', '0001_initial'),
        ('Lab_Radiology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineservice',
            name='medication_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MedicineService', to='Pharmacy.currentmedication'),
        ),
        migrations.AddField(
            model_name='insurancedetails',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InsuranceDetails', to='Hospital.patient'),
        ),
        migrations.AddField(
            model_name='examservice',
            name='bill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ExamService', to='Bills.bill'),
        ),
        migrations.AddField(
            model_name='examservice',
            name='exam_request_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ExamService', to='Lab_Radiology.examrequest'),
        ),
        migrations.AddField(
            model_name='bill',
            name='insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bill', to='Bills.insurancedetails'),
        ),
        migrations.AddField(
            model_name='bill',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bill', to='Hospital.patient'),
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='appointment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AppointmentService', to='Appointments.bookedappointment'),
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='bill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AppointmentService', to='Bills.bill'),
        ),
    ]
