# Generated by Django 4.1.7 on 2023-03-28 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bills', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
