# Generated by Django 4.1.7 on 2023-04-01 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
        ('Bills', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancedetails',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.patient'),
        ),
    ]
