# Generated by Django 4.1.7 on 2023-04-01 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Radiology', '0001_initial'),
        ('Hospital', '0001_initial'),
        ('Pharmacy', '0001_initial'),
        ('Bills', '0003_alter_insurancedetails_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_service',
            name='bill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bills.bill'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bills.insurancedetails'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.patient'),
        ),
        migrations.AlterField(
            model_name='exam_service',
            name='bill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bills.bill'),
        ),
        migrations.AlterField(
            model_name='exam_service',
            name='exam_request_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lab_Radiology.exam_request'),
        ),
        migrations.AlterField(
            model_name='medicine_service',
            name='bill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bills.bill'),
        ),
        migrations.AlterField(
            model_name='medicine_service',
            name='current_medicine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy.current_medication'),
        ),
    ]
