# Generated by Django 4.1.7 on 2023-04-06 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
        ('Appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedappointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_appointment', to='Hospital.doctor'),
        ),
        migrations.AlterField(
            model_name='bookedappointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_appointment', to='Hospital.patient'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='schedule_status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=10),
        ),
    ]
