# Generated by Django 4.1.7 on 2023-04-02 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Appointments', '0001_initial'),
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorschedule',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.doctor'),
        ),
        migrations.AddField(
            model_name='bookedappointment',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.doctor'),
        ),
        migrations.AddField(
            model_name='bookedappointment',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.patient'),
        ),
        migrations.AddField(
            model_name='bookedappointment',
            name='slot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Appointments.slot'),
        ),
    ]
