# Generated by Django 4.1.7 on 2023-03-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='email',
            field=models.EmailField(blank=1, max_length=254, null=1, unique=1),
        ),
    ]
