# Generated by Django 4.1.7 on 2023-04-03 04:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=255)),
                ('exam_type', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='ExamRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Requested', max_length=10)),
                ('dateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_exam', to='Hospital.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_exam', to='Hospital.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('result_value', models.DecimalField(decimal_places=5, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('min_reference_range', models.DecimalField(decimal_places=5, max_digits=10)),
                ('max_reference_range', models.DecimalField(decimal_places=5, max_digits=10)),
                ('comment', models.TextField(blank=True)),
                ('Request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_request', to='Lab_Radiology.examrequest')),
            ],
        ),
        migrations.CreateModel(
            name='RadiolgyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('image', models.ImageField(upload_to='Lab_Radiology/files/media')),
                ('report_file', models.FileField(upload_to='Lab_Radiology/files')),
                ('comment', models.TextField(blank=True)),
                ('Request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radiolgy_request', to='Lab_Radiology.examrequest')),
            ],
        ),
        migrations.CreateModel(
            name='LabRadiologyStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam', to='Lab_Radiology.examinationlist')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='Lab_Radiology.examrequest')),
            ],
        ),
    ]
