# Generated by Django 4.1.7 on 2023-04-01 10:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Requested', max_length=10)),
                ('dateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('doctor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Hospital.doctor')),
                ('patient', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Hospital.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Examination_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=255, null=True)),
                ('exam_type', models.CharField(max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Test_Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('result_value', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('unit', models.CharField(max_length=50, null=True)),
                ('min_reference_range', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('max_reference_range', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('comment', models.TextField(blank=True, max_length=3000, null=True)),
                ('Request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lab_Radiology.exam_request')),
            ],
        ),
        migrations.CreateModel(
            name='Radiolgy_Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('image', models.ImageField(upload_to='')),
                ('file', models.FileField(default='test', upload_to='')),
                ('comment', models.TextField(blank=True, max_length=3000)),
                ('Request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lab_Radiology.exam_request')),
            ],
        ),
        migrations.CreateModel(
            name='Exam_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Lab_Radiology.examination_list')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lab_Radiology.exam_request')),
            ],
        ),
    ]
