# Generated by Django 4.1.7 on 2023-04-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Radiology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinationlist',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
