# Generated by Django 4.1.7 on 2023-04-01 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
        ('Lab_Radiology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_request',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Hospital.doctor'),
        ),
        migrations.AlterField(
            model_name='exam_request',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.patient'),
        ),
    ]
